// ABOUTME: GENERATED by npm run watcher:abis from cctp/MockCCTPV2.sol/MockMessageTransmitterV2.json — do not edit.
// ABOUTME: Event-only ABI consumed by ponder.config.ts (spec §7.2).
export const MessageTransmitterAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "caller",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "sourceDomain",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "nonce",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "sender",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "finalityThresholdExecuted",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "messageBody",
        "type": "bytes"
      }
    ],
    "name": "MessageReceived",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "message",
        "type": "bytes"
      }
    ],
    "name": "MessageSent",
    "type": "event"
  }
] as const;
