// ABOUTME: GENERATED by npm run watcher:abis from privacy-pool/interfaces/IShieldModule.sol/IShieldModule.json, privacy-pool/interfaces/ITransactModule.sol/ITransactModule.json — do not edit.
// ABOUTME: Event-only ABI consumed by ponder.config.ts (spec §7.2).
export const PrivacyPoolAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "treeNumber",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "startPosition",
        "type": "uint256"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "npk",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "enum TokenType",
                "name": "tokenType",
                "type": "uint8"
              },
              {
                "internalType": "address",
                "name": "tokenAddress",
                "type": "address"
              },
              {
                "internalType": "uint256",
                "name": "tokenSubID",
                "type": "uint256"
              }
            ],
            "internalType": "struct TokenData",
            "name": "token",
            "type": "tuple"
          },
          {
            "internalType": "uint120",
            "name": "value",
            "type": "uint120"
          }
        ],
        "indexed": false,
        "internalType": "struct CommitmentPreimage[]",
        "name": "commitments",
        "type": "tuple[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32[3]",
            "name": "encryptedBundle",
            "type": "bytes32[3]"
          },
          {
            "internalType": "bytes32",
            "name": "shieldKey",
            "type": "bytes32"
          }
        ],
        "indexed": false,
        "internalType": "struct ShieldCiphertext[]",
        "name": "shieldCiphertext",
        "type": "tuple[]"
      },
      {
        "indexed": false,
        "internalType": "uint256[]",
        "name": "fees",
        "type": "uint256[]"
      }
    ],
    "name": "Shield",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "destinationDomain",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "nonce",
        "type": "uint64"
      }
    ],
    "name": "CrossChainUnshieldInitiated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "treeNumber",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "bytes32[]",
        "name": "nullifier",
        "type": "bytes32[]"
      }
    ],
    "name": "Nullified",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "treeNumber",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "startPosition",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32[]",
        "name": "hash",
        "type": "bytes32[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32[4]",
            "name": "ciphertext",
            "type": "bytes32[4]"
          },
          {
            "internalType": "bytes32",
            "name": "blindedSenderViewingKey",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "blindedReceiverViewingKey",
            "type": "bytes32"
          },
          {
            "internalType": "bytes",
            "name": "annotationData",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "memo",
            "type": "bytes"
          }
        ],
        "indexed": false,
        "internalType": "struct CommitmentCiphertext[]",
        "name": "ciphertext",
        "type": "tuple[]"
      }
    ],
    "name": "Transact",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "enum TokenType",
            "name": "tokenType",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenSubID",
            "type": "uint256"
          }
        ],
        "indexed": false,
        "internalType": "struct TokenData",
        "name": "token",
        "type": "tuple"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "fee",
        "type": "uint256"
      }
    ],
    "name": "Unshield",
    "type": "event"
  }
] as const;
