// ABOUTME: Generates watcher ABIs from Hardhat artifacts (`npm run watcher:abis`, spec §7.2):
// ABOUTME: fails loudly when artifacts are missing or drift from the checked-in copies.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Default artifact root: the monorepo clone (compile it there with `npm run compile`),
// falling back to a local artifacts/ dir. Override with HARDHAT_ARTIFACTS_DIR.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const ARTIFACTS_DIR =
  process.env.HARDHAT_ARTIFACTS_DIR ??
  join(ROOT, ".context", "armada-poc", "artifacts", "contracts");
const ABIS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "abis");

// contract artifact path (under artifacts/contracts) -> checked-in ABI module
// The hub pool is a router delegating to modules, so its indexed events live on the module
// interfaces; each output merges events from the listed artifacts.
const TARGETS = [
  {
    artifacts: [
      "privacy-pool/interfaces/IShieldModule.sol/IShieldModule.json",
      "privacy-pool/interfaces/ITransactModule.sol/ITransactModule.json",
    ],
    out: "PrivacyPool.ts",
    exportName: "PrivacyPoolAbi",
  },
  {
    artifacts: ["privacy-pool/interfaces/IPrivacyPoolClient.sol/IPrivacyPoolClient.json"],
    out: "PrivacyPoolClient.ts",
    exportName: "PrivacyPoolClientAbi",
  },
  {
    // MockCCTPV2 matches real CCTP v2 event shapes (monorepo comment); on mainnet diff
    // against Circle's published MessageTransmitterV2 ABI.
    artifacts: ["cctp/MockCCTPV2.sol/MockMessageTransmitterV2.json"],
    out: "MessageTransmitter.ts",
    exportName: "MessageTransmitterAbi",
  },
];

const CHECK_ONLY = process.argv.includes("--check");
let failed = false;

for (const target of TARGETS) {
  const events = [];
  let missing = false;
  for (const rel of target.artifacts) {
    const artifactPath = join(ARTIFACTS_DIR, rel);
    if (!existsSync(artifactPath)) {
      console.error(
        `ERROR: missing Hardhat artifact ${artifactPath}. Compile the monorepo first ` +
          `(npm run compile in .context/armada-poc), or set HARDHAT_ARTIFACTS_DIR ` +
          `(manual ABI editing is prohibited, spec §7.2).`,
      );
      missing = true;
      continue;
    }
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
    events.push(...artifact.abi.filter((item) => item.type === "event"));
  }
  if (missing) {
    failed = true;
    continue;
  }
  const body =
    `// ABOUTME: GENERATED by npm run watcher:abis from ${target.artifacts.join(", ")} — do not edit.\n` +
    `// ABOUTME: Event-only ABI consumed by ponder.config.ts (spec §7.2).\n` +
    `export const ${target.exportName} = ${JSON.stringify(events, null, 2)} as const;\n`;
  const outPath = join(ABIS_DIR, target.out);
  if (CHECK_ONLY) {
    if (!existsSync(outPath) || readFileSync(outPath, "utf8") !== body) {
      console.error(`ERROR: ${target.out} drifts from the built artifact. Run npm run watcher:abis.`);
      failed = true;
    }
  } else {
    writeFileSync(outPath, body);
    console.log(`wrote ${outPath} (${events.length} events)`);
  }
}

process.exit(failed ? 1 : 0);
