// ABOUTME: Generates watcher ABIs from Hardhat artifacts (`npm run watcher:abis`, spec §7.2):
// ABOUTME: fails loudly when artifacts are missing or drift from the checked-in copies.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const ARTIFACTS_DIR = process.env.HARDHAT_ARTIFACTS_DIR ?? join(ROOT, "artifacts", "contracts");
const ABIS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "abis");

// contract artifact path (under artifacts/contracts) -> checked-in ABI module
const TARGETS = [
  { artifact: "PrivacyPool.sol/PrivacyPool.json", out: "PrivacyPool.ts", exportName: "PrivacyPoolAbi" },
  { artifact: "PrivacyPoolClient.sol/PrivacyPoolClient.json", out: "PrivacyPoolClient.ts", exportName: "PrivacyPoolClientAbi" },
  { artifact: "MessageTransmitter.sol/MessageTransmitter.json", out: "MessageTransmitter.ts", exportName: "MessageTransmitterAbi" },
];

const CHECK_ONLY = process.argv.includes("--check");
let failed = false;

for (const target of TARGETS) {
  const artifactPath = join(ARTIFACTS_DIR, target.artifact);
  if (!existsSync(artifactPath)) {
    console.error(
      `ERROR: missing Hardhat artifact ${artifactPath}. Build the contracts first ` +
        `(manual ABI editing is prohibited, spec §7.2). Set HARDHAT_ARTIFACTS_DIR if the ` +
        `artifacts live elsewhere. NOTE: the currently checked-in ABIs are hand-authored ` +
        `placeholders (DEV-3 in .context/deviations.md) pending real artifacts.`,
    );
    failed = true;
    continue;
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const events = artifact.abi.filter((item) => item.type === "event");
  const body =
    `// ABOUTME: GENERATED by npm run watcher:abis from ${target.artifact} — do not edit.\n` +
    `// ABOUTME: Event-only ABI consumed by ponder.config.ts (spec §7.2).\n` +
    `export const ${target.exportName} = ${JSON.stringify(events, null, 2)} as const;\n`;
  const outPath = join(ABIS_DIR, target.out);
  if (CHECK_ONLY) {
    if (!existsSync(outPath) || readFileSync(outPath, "utf8") !== body) {
      console.error(`ERROR: ${target.out} drifts from the built artifact. Run npm run watcher:abis.`);
      failed = true;
    }
  } else {
    writeFileSync(outPath, body);
    console.log(`wrote ${outPath} (${events.length} events)`);
  }
}

process.exit(failed ? 1 : 0);
